sudo: required
services: 
  - docker

before_install:
  - docker build -t almiskea/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run almiskea/react-test npm test -- --coverage

after_success:
  - docker build -t almiskea/multi-client ./client
  - docker build -t almiskea/multi-nginx ./nginx
  - docker build -t almiskea/multi-server ./OktaDemo
  - docker build -t almiskea/multi-worker ./Worker
  #Login to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push
  - docker push almiskea/multi-client
  - docker push almiskea/multi-nginx
  - docker push almiskea/multi-server
  - docker push almiskea/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "multi-docker-java"
  env: "MultiDockerJava-env"
  bucket_name: "elasticbeanstalk-us-west-2-619677518466"
  bucket_path: "docker-multi"
  on:
    branch: production
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECERT_KEY